# Practice for Module 3

The learning goals for this module is centered around Array Oriented Programming:
* Writing vectorization code
* NumPy
    - Arithmetic with arrays
    - Slicining higher dimensional arrays
* The Lambda Expression
* The Reduce Function
* Solving complicated problems without the use of loops

## NumPy

In [38]:
import numpy as np
my_arr = np.arange(100) # NumPy array
my_list = list(range(100)) # Python list
print(my_arr)
print(my_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [39]:
# Time for NumpPy operation
my_arr = np.arange(100)
%time for _ in range(2): my_arr2 = my_arr * 2
print(my_arr2)

CPU times: total: 0 ns
Wall time: 87.3 μs
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [40]:
# List practice
my_list2 = [i ** 2 for i in my_list]
print(my_list2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


## Vectorized arrays

In [41]:
import numpy as np
samplelist = [1, 2, 3, 4, 5]
samplearray = np.array(samplelist)
print(type(samplearray))


<class 'numpy.ndarray'>


Add 2 to every value in the list/array

In [42]:
try:
    samplelist += 2
except TypeError:
    print("Incompatible types")

Incompatible types


In [43]:
samplearray += 2
print(samplearray)

[3 4 5 6 7]


## NumPy ndarray

Performs mathematical operations on blocks of data. It is a container for homogenous data. Every array has a shape: a tuple indicating the size of each dimension, and a dtype: an object describing the data type of the array

In [44]:
my_ndarray = np.arange(5)
print(my_ndarray)

[0 1 2 3 4]


In [45]:
print(my_ndarray+5)

[5 6 7 8 9]


In [46]:
print(my_ndarray ** 3)

[ 0  1  8 27 64]


Random function and ndarray methods

In [47]:
data_rand = np.random.randn(3,4)
print("Starting ndarray : {0}".format(data_rand))
print()
print("Multiply by 10 : {0}".format(data_rand * 10))
print("Shape of ndarray : {0}".format(data_rand.shape))
print(f"Type of data: {data_rand.dtype}")
print(f"Number of dimensions: {data_rand.ndim}")

Starting ndarray : [[-0.31326038 -0.11459147  0.65995245  0.39843676]
 [ 0.45357684  0.53950544  2.53523177 -2.24907536]
 [ 0.58707053 -0.74663289  0.62887911 -0.01681048]]

Multiply by 10 : [[ -3.13260376  -1.14591471   6.59952446   3.98436759]
 [  4.53576837   5.39505441  25.35231771 -22.49075365]
 [  5.87070528  -7.46632893   6.28879109  -0.16810478]]
Shape of ndarray : (3, 4)
Type of data: float64
Number of dimensions: 2


Creation of ndarrays

In [48]:
# From list
list_input = [1, 2, 3, 4, 5]
ndarray_from_list = np.array(list_input)
print(type(ndarray_from_list))
print(ndarray_from_list)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [49]:
# From two-dimensional list
two_dim_list = [[1,2,3],[4,5,6],[7,8,9]]
ndarray_from_2dlist = np.array(two_dim_list)
print(ndarray_from_2dlist)
print(ndarray_from_2dlist.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [50]:
# Instantiate an empty ndarray
empty_ndarray_test = np.empty((3,4,5))

# Initialize an ndarray of all zeros
zeros_ndarray_test = np.zeros((3,4,5))

# Compare time to instantiate empty vs zeros
avg_empty_time = %timeit -o empty_ndarray = np.empty((1000,1000,100))
avg_zeros_time = %timeit -o zeros_ndarray = np.zeros((1000,1000,100))
empty_ndarray = np.empty((1000,1000,100))
zeros_ndarray = np.zeros((1000,1000,100))

23.3 μs ± 1.21 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
25.1 μs ± 1.15 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [51]:
# Checking data id
print(f"ID of empty ndarray: {id(empty_ndarray)}")
print(f'ID of 333,222,11 element in zeros ndarray: {id(zeros_ndarray[333][222][11])}')
print(f'ID of 333,222,12 element in zeros ndarray: {id(zeros_ndarray[333][222][12])}')

ID of empty ndarray: 2099854839600
ID of 333,222,11 element in zeros ndarray: 2099854448720
ID of 333,222,12 element in zeros ndarray: 2099854448720


NumPy Data Types
* dtype contains the information (metadata) the ndarray needs to interpret a chunk of memory as a particular data type
* the naming convention is the type of data followed by the number of bits per element. Eg int32, float64

In [52]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.int32)
print(arr1)
print(arr1.dtype)
arr2 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
int32
float64


## Arithmetic with NumPy arrays

In [53]:
arith_arr = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
print(f"Array squared: {arith_arr ** 2}")

Array squared: [[ 1.  4.  9.]
 [16. 25. 36.]]


## Basic indexing and slicing

In [54]:
slice_arr = np.arange(2,114,2).reshape((7,8))
print(slice_arr)

[[  2   4   6   8  10  12  14  16]
 [ 18  20  22  24  26  28  30  32]
 [ 34  36  38  40  42  44  46  48]
 [ 50  52  54  56  58  60  62  64]
 [ 66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96]
 [ 98 100 102 104 106 108 110 112]]


In [55]:
print(slice_arr[3:5, 4:6])  # Rows 3 and 4, Columns 4 and 5

[[58 60]
 [74 76]]


In [57]:
slice_arr[5:, 6:] = 99
print(slice_arr)

[[  2   4   6   8  10  12  14  16]
 [ 18  20  22  24  26  28  30  32]
 [ 34  36  38  40  42  44  46  48]
 [ 50  52  54  56  58  60  62  64]
 [ 66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  99  99]
 [ 98 100 102 104 106 108  99  99]]


In [62]:
slice_arr[:2,:2] = 11
print(slice_arr)
print(slice_arr[0,0])  # First row, first column

[[ 11  11   6   8  10  12  14  16]
 [ 11  11  22  24  26  28  30  32]
 [ 34  36  38  40  42  44  46  48]
 [ 50  52  54  56  58  60  62  64]
 [ 66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  99  99]
 [ 98 100 102 104 106 108  99  99]]
11


### Notes
* slicing includes the start value and excludes the end value
* the first index is zero

## Boolean Indexing

In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names == 'Bob')
print(names[names == 'Bob'])
print(names[names != 'Bob'])
print(names[np.array([True, False, False, False, True, False, True])])


[ True False False  True False False False]
['Bob' 'Bob']
['Joe' 'Will' 'Will' 'Joe' 'Joe']
['Bob' 'Will' 'Joe']


In [ ]:
names[names != 'Bob'] = 'Co'
print(names)

['Bob' 'Cole' 'Cole' 'Bob' 'Cole' 'Cole' 'Cole']
